services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: tabitabi
      POSTGRES_PASSWORD: tabitabi
      POSTGRES_DB: tabitabi
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: